package ar.edu.unlu.zombie.modelo.enumerados;

import java.io.Serializable;

public enum EventoGeneral implements Serializable {	
	MOSTRAR_PANTALLA_NOMBRES_JUGADORES_CARGADOS,
	MOSTRAR_PANTALLA_RONDA_JUGADORES,
	CONTINUAR_SIGUIENTE_TURNO_RONDA,
	FINAL_RONDA,
	MOSTRAR_PANTALLA_MENU_PRINCIPAL,
	PARTIDA_PERSISTIDA,
	ERROR_PARTIDA_PERSISTIDA,
	MOSTRAR_PANTALLA_NOMBRES_JUGADORES_PARTIDA_RECUPERADA,
	ERROR_PARTIDA_RECUPERADA
}
